# Generated by Django 5.2.3 on 2025-07-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(max_length=15, null=True),
        ),
    ]
