# Generated by Django 5.2.3 on 2025-07-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_studentuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='gender',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='type',
            field=models.CharField(default='student', max_length=15),
        ),
    ]
