# Generated by Django 5.2.3 on 2025-07-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_recruiteruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='user_resumes/'),
        ),
    ]
